export type Product = {
  id: string;
  brand: "Apple" | "Samsung";
  name: string;
  model: string;
  price: number;
  image: string;
  imageLabel: string;
  badge?: string;
  warranty: string;
};

export const products: Product[] = [
  {
    id: "iphone-17-pro-max",
    brand: "Apple",
    name: "iPhone 17 Pro Max",
    model: "iSYSTEMS Jordan Warranty",
    price: 1209,
    image: "/assets/iphone17promax.jpg",
    imageLabel: "iPhone 17 Pro Max",
    badge: "Premium",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-17-pro",
    brand: "Apple",
    name: "iPhone 17 Pro",
    model: "iSYSTEMS Jordan Warranty",
    price: 1109,
    image: "/assets/iphone17pro.jpg",
    imageLabel: "iPhone 17 Pro",
    badge: "Pro",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-air",
    brand: "Apple",
    name: "iPhone Air",
    model: "iSYSTEMS Jordan Warranty",
    price: 849,
    image: "/assets/iphoneair.jpg",
    imageLabel: "iPhone Air",
    badge: "جديد",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-17",
    brand: "Apple",
    name: "iPhone 17",
    model: "iSYSTEMS Jordan Warranty",
    price: 809,
    image: "/assets/iphone17.jpg",
    imageLabel: "iPhone 17",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-17e",
    brand: "Apple",
    name: "iPhone 17e",
    model: "iSYSTEMS Jordan Warranty",
    price: 609,
    image: "/assets/iphone17e.jpg",
    imageLabel: "iPhone 17e",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16-pro-max",
    brand: "Apple",
    name: "iPhone 16 Pro Max",
    model: "iSYSTEMS Jordan Warranty",
    price: 1049,
    image: "/assets/iphone16promax.jpg",
    imageLabel: "iPhone 16 Pro Max",
    badge: "قوي",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16-pro",
    brand: "Apple",
    name: "iPhone 16 Pro",
    model: "iSYSTEMS Jordan Warranty",
    price: 949,
    image: "/assets/iphone16pro.jpg",
    imageLabel: "iPhone 16 Pro",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16-plus",
    brand: "Apple",
    name: "iPhone 16 Plus",
    model: "iSYSTEMS Jordan Warranty",
    price: 779,
    image: "/assets/iphone16plus.jpg",
    imageLabel: "iPhone 16 Plus",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16",
    brand: "Apple",
    name: "iPhone 16",
    model: "iSYSTEMS Jordan Warranty",
    price: 689,
    image: "/assets/iphone16.jpg",
    imageLabel: "iPhone 16",
    badge: "عرض",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16e",
    brand: "Apple",
    name: "iPhone 16e",
    model: "iSYSTEMS Jordan Warranty",
    price: 549,
    image: "/assets/iphone16e.jpg",
    imageLabel: "iPhone 16e",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-15-plus",
    brand: "Apple",
    name: "iPhone 15 Plus",
    model: "iSYSTEMS Jordan Warranty",
    price: 649,
    image: "/assets/iphone15plus.jpg",
    imageLabel: "iPhone 15 Plus",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-15",
    brand: "Apple",
    name: "iPhone 15",
    model: "iSYSTEMS Jordan Warranty",
    price: 599,
    image: "/assets/iphone15.jpg",
    imageLabel: "iPhone 15",
    warranty: "iSYSTEMS الأردن",
  },

  {
    id: "s26-ultra-5g",
    brand: "Samsung",
    name: "S26 Ultra 5G",
    model: "BMS Samsung Warranty",
    price: 969,
    image: "/assets/s26ultra.jpg",
    imageLabel: "S26 Ultra",
    badge: "جديد",
    warranty: "BMS Samsung",
  },
  {
    id: "s26-plus-5g",
    brand: "Samsung",
    name: "S26+ 5G",
    model: "BMS Samsung Warranty",
    price: 949,
    image: "/assets/s26plus.jpg",
    imageLabel: "S26+",
    badge: "جديد",
    warranty: "BMS Samsung",
  },
  {
    id: "s25-ultra-5g-sm-s938b",
    brand: "Samsung",
    name: "S25 Ultra 5G",
    model: "SM-S938B",
    price: 760,
    image: "/assets/s25ultra.jpg",
    imageLabel: "S25 Ultra",
    badge: "الأكثر طلبًا",
    warranty: "BMS Samsung",
  },
  {
    id: "s25-plus-5g-sm-s936b",
    brand: "Samsung",
    name: "S25+ 5G",
    model: "SM-S936B",
    price: 690,
    image: "/assets/s25plus.jpg",
    imageLabel: "S25+",
    warranty: "BMS Samsung",
  },
  {
    id: "s25-5g-sm-s931b",
    brand: "Samsung",
    name: "S25 5G",
    model: "SM-S931B",
    price: 566,
    image: "/assets/s25.jpg",
    imageLabel: "S25",
    warranty: "BMS Samsung",
  },
  {
    id: "s24-ultra-5g",
    brand: "Samsung",
    name: "S24 Ultra 5G",
    model: "BMS Samsung Warranty",
    price: 699,
    image: "/assets/s24ultra.jpg",
    imageLabel: "S24 Ultra",
    warranty: "BMS Samsung",
  },
  {
    id: "s24-plus-5g-sm-s926",
    brand: "Samsung",
    name: "S24+ 5G",
    model: "SM-S926",
    price: 699,
    image: "/assets/s24plus.jpg",
    imageLabel: "S24+",
    warranty: "BMS Samsung",
  },
  {
    id: "s24-5g-sm-s921",
    brand: "Samsung",
    name: "S24 5G",
    model: "SM-S921",
    price: 566,
    image: "/assets/s24.jpg",
    imageLabel: "S24",
    warranty: "BMS Samsung",
  },
  {
    id: "z-flip7-5g-sm-f766b",
    brand: "Samsung",
    name: "Z Flip7 5G",
    model: "SM-F766B",
    price: 799,
    image: "/assets/zflip7.jpg",
    imageLabel: "Z Flip7",
    badge: "Flip",
    warranty: "BMS Samsung",
  },
  {
    id: "a56-5g-sm-a566b",
    brand: "Samsung",
    name: "A56 5G",
    model: "SM-A566B",
    price: 235,
    image: "/assets/a56.jpg",
    imageLabel: "A56",
    warranty: "BMS Samsung",
  },
];

export function getProductById(id: string | null | undefined) {
  if (!id) return null;

  return products.find((product) => product.id === id) || null;
}