export type Product = {
  id: string;
  brand: "Apple" | "Samsung" | "HONOR" | "TECNO";
  name: string;
  model: string;
  price: number;
  image: string;
  imageLabel: string;
  badge?: string;
  warranty: string;
};

export const products: Product[] = [
  {
    id: "iphone-17-pro-max",
    brand: "Apple",
    name: "iPhone 17 Pro Max",
    model: "256GB",
    price: 1209,
    image: "/assets/iphone17promax.jpg",
    imageLabel: "iPhone 17 Pro Max",
    badge: "Premium",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-17-pro",
    brand: "Apple",
    name: "iPhone 17 Pro",
    model: "256GB",
    price: 1109,
    image: "/assets/iphone17pro.jpg",
    imageLabel: "iPhone 17 Pro",
    badge: "Pro",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-air",
    brand: "Apple",
    name: "iPhone Air",
    model: "256GB",
    price: 849,
    image: "/assets/iphoneair.jpg",
    imageLabel: "iPhone Air",
    badge: "جديد",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-17",
    brand: "Apple",
    name: "iPhone 17",
    model: "256GB",
    price: 809,
    image: "/assets/iphone17.jpg",
    imageLabel: "iPhone 17",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-17e",
    brand: "Apple",
    name: "iPhone 17e",
    model: "256GB",
    price: 609,
    image: "/assets/iphone17e.jpg",
    imageLabel: "iPhone 17e",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16-pro-max",
    brand: "Apple",
    name: "iPhone 16 Pro Max",
    model: "256GB",
    price: 1049,
    image: "/assets/iphone16promax.jpg",
    imageLabel: "iPhone 16 Pro Max",
    badge: "قوي",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16-pro",
    brand: "Apple",
    name: "iPhone 16 Pro",
    model: "256GB",
    price: 949,
    image: "/assets/iphone16pro.jpg",
    imageLabel: "iPhone 16 Pro",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16-plus",
    brand: "Apple",
    name: "iPhone 16 Plus",
    model: "256GB",
    price: 779,
    image: "/assets/iphone16plus.jpg",
    imageLabel: "iPhone 16 Plus",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16",
    brand: "Apple",
    name: "iPhone 16",
    model: "256GB",
    price: 689,
    image: "/assets/iphone16.jpg",
    imageLabel: "iPhone 16",
    badge: "عرض",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-16e",
    brand: "Apple",
    name: "iPhone 16e",
    model: "256GB",
    price: 549,
    image: "/assets/iphone16e.jpg",
    imageLabel: "iPhone 16e",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-15-plus",
    brand: "Apple",
    name: "iPhone 15 Plus",
    model: "256GB",
    price: 649,
    image: "/assets/iphone15plus.jpg",
    imageLabel: "iPhone 15 Plus",
    warranty: "iSYSTEMS الأردن",
  },
  {
    id: "iphone-15",
    brand: "Apple",
    name: "iPhone 15",
    model: "256GB",
    price: 599,
    image: "/assets/iphone15.jpg",
    imageLabel: "iPhone 15",
    warranty: "iSYSTEMS الأردن",
  },

  {
    id: "s26-ultra-5g",
    brand: "Samsung",
    name: "S26 Ultra 5G",
    model: "256GB",
    price: 969,
    image: "/assets/s26ultra.jpg",
    imageLabel: "S26 Ultra",
    badge: "جديد",
    warranty: "BMS Samsung",
  },
  {
    id: "s26-plus-5g",
    brand: "Samsung",
    name: "S26+ 5G",
    model: "256GB",
    price: 949,
    image: "/assets/s26plus.jpg",
    imageLabel: "S26+",
    badge: "جديد",
    warranty: "BMS Samsung",
  },
  {
    id: "s25-ultra-5g-sm-s938b",
    brand: "Samsung",
    name: "S25 Ultra 5G",
    model: "256GB",
    price: 760,
    image: "/assets/s25ultra.jpg",
    imageLabel: "S25 Ultra",
    badge: "الأكثر طلبًا",
    warranty: "BMS Samsung",
  },
  {
    id: "s25-plus-5g-sm-s936b",
    brand: "Samsung",
    name: "S25+ 5G",
    model: "256GB",
    price: 690,
    image: "/assets/s25plus.jpg",
    imageLabel: "S25+",
    warranty: "BMS Samsung",
  },
  {
    id: "s25-5g-sm-s931b",
    brand: "Samsung",
    name: "S25 5G",
    model: "256GB",
    price: 566,
    image: "/assets/s25.jpg",
    imageLabel: "S25",
    warranty: "BMS Samsung",
  },
  {
    id: "s24-ultra-5g",
    brand: "Samsung",
    name: "S24 Ultra 5G",
    model: "256GB",
    price: 699,
    image: "/assets/s24ultra.jpg",
    imageLabel: "S24 Ultra",
    warranty: "BMS Samsung",
  },
  {
    id: "s24-plus-5g-sm-s926",
    brand: "Samsung",
    name: "S24+ 5G",
    model: "256GB",
    price: 699,
    image: "/assets/s24plus.jpg",
    imageLabel: "S24+",
    warranty: "BMS Samsung",
  },
  {
    id: "s24-5g-sm-s921",
    brand: "Samsung",
    name: "S24 5G",
    model: "256GB",
    price: 566,
    image: "/assets/s24.jpg",
    imageLabel: "S24",
    warranty: "BMS Samsung",
  },
  {
    id: "z-flip7-5g-sm-f766b",
    brand: "Samsung",
    name: "Z Flip7 5G",
    model: "256GB",
    price: 799,
    image: "/assets/zflip7.jpg",
    imageLabel: "Z Flip7",
    badge: "Flip",
    warranty: "BMS Samsung",
  },
  {
    id: "a56-5g-sm-a566b",
    brand: "Samsung",
    name: "A56 5G",
    model: "256GB",
    price: 235,
    image: "/assets/a56.jpg",
    imageLabel: "A56",
    warranty: "BMS Samsung",
  },

  {
    id: "honor-600-pro",
    brand: "HONOR",
    name: "HONOR 600 Pro",
    model: "256GB",
    price: 599,
    image: "/assets/HOnor600pro.jpg",
    imageLabel: "HONOR 600 Pro",
    badge: "Pro",
    warranty: "كفالة Cell Avenue",
  },
  {
    id: "honor-600",
    brand: "HONOR",
    name: "HONOR 600",
    model: "256GB",
    price: 379,
    image: "/assets/HONOR-600.jpg",
    imageLabel: "HONOR 600",
    badge: "جديد",
    warranty: "كفالة Cell Avenue",
  },
  {
    id: "honor-600-lite",
    brand: "HONOR",
    name: "HONOR 600 Lite",
    model: "256GB",
    price: 239,
    image: "/assets/HONOR-600lite.jpg",
    imageLabel: "HONOR 600 Lite",
    badge: "256GB",
    warranty: "كفالة Cell Avenue",
  },
  {
    id: "honor-x9d",
    brand: "HONOR",
    name: "HONOR X9d",
    model: "256GB",
    price: 249,
    image: "/assets/x9d.jpg",
    imageLabel: "HONOR X9d",
    badge: "8300mAh",
    warranty: "كفالة Cell Avenue",
  },

  {
    id: "tecno-camon-40",
    brand: "TECNO",
    name: "TECNO CAMON 40",
    model: "256GB",
    price: 179,
    image: "/assets/tecnocamon40.png",
    imageLabel: "TECNO CAMON 40",
    badge: "CAMON",
    warranty: "كفالة Reach / الشروق",
  },
  {
    id: "tecno-camon-40-pro",
    brand: "TECNO",
    name: "TECNO CAMON 40 Pro 5G",
    model: "256GB",
    price: 235,
    image: "/assets/tecnocamon40pro.png",
    imageLabel: "TECNO CAMON 40 Pro 5G",
    badge: "5G",
    warranty: "كفالة Reach / الشروق",
  },
  {
    id: "tecno-pova-7-ultra",
    brand: "TECNO",
    name: "TECNO POVA 7 Ultra 5G",
    model: "256GB",
    price: 289,
    image: "/assets/tecnopova7ultra.png",
    imageLabel: "TECNO POVA 7 Ultra 5G",
    badge: "Ultra",
    warranty: "كفالة Reach / الشروق",
  },
  {
    id: "tecno-spark-30-5g",
    brand: "TECNO",
    name: "TECNO SPARK 30 5G",
    model: "128GB",
    price: 120,
    image: "/assets/tecnospark305G.png",
    imageLabel: "TECNO SPARK 30 5G",
    badge: "128GB",
    warranty: "كفالة Reach / الشروق",
  },
];

export function getProductById(id: string | null | undefined) {
  if (!id) return null;

  return products.find((product) => product.id === id) || null;
}