-- ALAMEEN V2.0 Conversation OS — Phase 0 + Phase 1 (SHADOW ONLY)
-- Date: 2026-08-30
-- Purpose:
--   1) restore observable Shadow worker health;
--   2) add the isolated V2 conversation-understanding queue/state store;
--   3) kick Shadow workers asynchronously after enqueue so jobs do not sit at attempt_count=0.
--
-- IMPORTANT:
-- - Additive only. It does NOT change applications/payment/refund/customer state.
-- - It does NOT send any V2 reply to customers.
-- - This migration is MANDATORY for the V2 Phase 0+1 code path to run.
-- - Run only on the intended Al-Ameen production Supabase project.

set search_path = public, extensions;

do $$
begin
  if to_regclass('public.applications') is null then
    raise exception 'WRONG DATABASE: public.applications is missing';
  end if;
  if to_regclass('public.whatsapp_shadow_jobs') is null then
    raise exception 'WRONG DATABASE / MISSING BASE MIGRATION: public.whatsapp_shadow_jobs is missing';
  end if;
  if to_regclass('public.whatsapp_shadow_settings') is null then
    raise exception 'WRONG DATABASE / MISSING BASE MIGRATION: public.whatsapp_shadow_settings is missing';
  end if;
end $$;

create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_net;

create table if not exists public.whatsapp_v2_conversation_states (
  wa_id text primary key,
  version text not null default '2.0-phase1',
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.whatsapp_v2_conversation_states enable row level security;

create table if not exists public.whatsapp_v2_shadow_jobs (
  id uuid primary key default gen_random_uuid(),
  incoming_message_id text not null unique,
  wa_id text not null,
  customer_name text,
  customer_message text not null,
  message_type text not null default 'text',
  actual_reply text not null,
  initial_intent text,
  tracking_id text,
  application_id text,
  application_snapshot jsonb not null default '{}'::jsonb,
  conversation_snapshot jsonb not null default '{}'::jsonb,

  status text not null default 'queued'
    check (status in ('queued','processing','retry_wait','succeeded','needs_review','dead_letter')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 3 check (max_attempts between 1 and 10),
  next_attempt_at timestamptz default now(),
  locked_at timestamptz,
  locked_by text,

  interpretation jsonb,
  resolved_turn jsonb,
  state_before jsonb,
  state_after jsonb,

  understanding_score integer not null default 0 check (understanding_score between 0 and 100),
  required_topics text[] not null default '{}',
  covered_topics text[] not null default '{}',
  missing_topics text[] not null default '{}',
  critical_flags text[] not null default '{}',
  warnings text[] not null default '{}',

  interpreter_model text,
  interpreter_ms integer,
  interpreter_error_code text,
  interpreter_error_message text,

  last_error_code text,
  last_error_message text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.whatsapp_v2_shadow_jobs enable row level security;

create index if not exists whatsapp_v2_shadow_jobs_due_idx
  on public.whatsapp_v2_shadow_jobs (status, next_attempt_at, created_at);
create index if not exists whatsapp_v2_shadow_jobs_wa_idx
  on public.whatsapp_v2_shadow_jobs (wa_id, created_at);
create index if not exists whatsapp_v2_shadow_jobs_created_idx
  on public.whatsapp_v2_shadow_jobs (created_at desc);

create table if not exists public.whatsapp_v2_shadow_attempts (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.whatsapp_v2_shadow_jobs(id) on delete cascade,
  job_attempt integer not null,
  model text,
  latency_ms integer,
  outcome text not null
    check (outcome in ('success','provider_fallback','worker_error')),
  error_code text,
  error_message text,
  interpretation_source text,
  created_at timestamptz not null default now()
);

alter table public.whatsapp_v2_shadow_attempts enable row level security;

create index if not exists whatsapp_v2_shadow_attempts_job_idx
  on public.whatsapp_v2_shadow_attempts (job_id, created_at desc);

create or replace function public.enqueue_whatsapp_v2_shadow_job(
  p_incoming_message_id text,
  p_wa_id text,
  p_customer_name text,
  p_customer_message text,
  p_message_type text,
  p_actual_reply text,
  p_initial_intent text,
  p_tracking_id text,
  p_application_id text,
  p_application_snapshot jsonb,
  p_conversation_snapshot jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if coalesce(trim(p_incoming_message_id), '') = '' then
    raise exception 'p_incoming_message_id is required';
  end if;
  if coalesce(trim(p_wa_id), '') = '' then
    raise exception 'p_wa_id is required';
  end if;

  insert into public.whatsapp_v2_shadow_jobs (
    incoming_message_id,
    wa_id,
    customer_name,
    customer_message,
    message_type,
    actual_reply,
    initial_intent,
    tracking_id,
    application_id,
    application_snapshot,
    conversation_snapshot,
    status,
    next_attempt_at
  )
  values (
    p_incoming_message_id,
    p_wa_id,
    p_customer_name,
    coalesce(p_customer_message, ''),
    coalesce(nullif(p_message_type, ''), 'text'),
    coalesce(p_actual_reply, ''),
    p_initial_intent,
    p_tracking_id,
    p_application_id,
    coalesce(p_application_snapshot, '{}'::jsonb),
    coalesce(p_conversation_snapshot, '{}'::jsonb),
    'queued',
    now()
  )
  on conflict (incoming_message_id) do nothing
  returning id into v_id;

  if v_id is null then
    select id into v_id
    from public.whatsapp_v2_shadow_jobs
    where incoming_message_id = p_incoming_message_id
    limit 1;
  end if;

  return v_id;
end;
$$;

revoke all on function public.enqueue_whatsapp_v2_shadow_job(
  text,text,text,text,text,text,text,text,text,jsonb,jsonb
) from public, anon, authenticated;
grant execute on function public.enqueue_whatsapp_v2_shadow_job(
  text,text,text,text,text,text,text,text,text,jsonb,jsonb
) to service_role;

create or replace function public.claim_whatsapp_v2_shadow_jobs(
  p_worker_id text,
  p_limit integer default 2
)
returns setof public.whatsapp_v2_shadow_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with selected as (
    select id
    from public.whatsapp_v2_shadow_jobs
    where status in ('queued','retry_wait')
      and coalesce(next_attempt_at, now()) <= now()
      and attempt_count < max_attempts
    order by created_at asc
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 2), 5))
  ), claimed as (
    update public.whatsapp_v2_shadow_jobs j
    set status = 'processing',
        attempt_count = j.attempt_count + 1,
        locked_at = now(),
        locked_by = p_worker_id,
        updated_at = now()
    from selected s
    where j.id = s.id
    returning j.*
  )
  select * from claimed;
end;
$$;

revoke all on function public.claim_whatsapp_v2_shadow_jobs(text, integer) from public, anon, authenticated;
grant execute on function public.claim_whatsapp_v2_shadow_jobs(text, integer) to service_role;

create or replace function public.requeue_stale_whatsapp_v2_shadow_jobs(
  p_stale_minutes integer default 10
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  update public.whatsapp_v2_shadow_jobs
  set status = case when attempt_count >= max_attempts then 'dead_letter' else 'retry_wait' end,
      next_attempt_at = case when attempt_count >= max_attempts then null else now() end,
      last_error_code = coalesce(last_error_code, 'stale_worker_lock'),
      last_error_message = coalesce(last_error_message, 'V2 shadow worker lock expired and was released.'),
      locked_at = null,
      locked_by = null,
      completed_at = case when attempt_count >= max_attempts then now() else completed_at end,
      updated_at = now()
  where status = 'processing'
    and locked_at < now() - make_interval(mins => greatest(1, coalesce(p_stale_minutes, 10)));

  get diagnostics affected = row_count;
  return affected;
end;
$$;

revoke all on function public.requeue_stale_whatsapp_v2_shadow_jobs(integer) from public, anon, authenticated;
grant execute on function public.requeue_stale_whatsapp_v2_shadow_jobs(integer) to service_role;

-- Phase 0: async kick after queue inserts. This is the primary antidote to silent attempt_count=0 backlogs.
create or replace function public.kick_alameen_shadow_worker()
returns trigger
language plpgsql
security definer
set search_path = public, net
as $$
declare
  v_token text;
  v_url text;
begin
  select value into v_token
  from public.whatsapp_shadow_settings
  where key = 'worker_token';

  if coalesce(v_token, '') = '' then
    return new;
  end if;

  if tg_table_name = 'whatsapp_v2_shadow_jobs' then
    v_url := 'https://www.ameenfinance.co/api/internal/whatsapp-v2-shadow/worker';
  else
    v_url := 'https://www.ameenfinance.co/api/internal/whatsapp-shadow/worker';
  end if;

  begin
    perform net.http_post(
      url := v_url,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-shadow-worker-token', v_token
      ),
      body := jsonb_build_object(
        'source', 'queue_insert_trigger',
        'table', tg_table_name
      )
    );
  exception when others then
    -- Queue insertion must never fail because the async kicker failed.
    raise warning 'Shadow worker kick failed for %: %', tg_table_name, sqlerrm;
  end;

  return new;
end;
$$;

drop trigger if exists trg_kick_legacy_whatsapp_shadow_worker on public.whatsapp_shadow_jobs;
create trigger trg_kick_legacy_whatsapp_shadow_worker
after insert on public.whatsapp_shadow_jobs
for each row
execute function public.kick_alameen_shadow_worker();

drop trigger if exists trg_kick_v2_whatsapp_shadow_worker on public.whatsapp_v2_shadow_jobs;
create trigger trg_kick_v2_whatsapp_shadow_worker
after insert on public.whatsapp_v2_shadow_jobs
for each row
execute function public.kick_alameen_shadow_worker();

-- Backup scheduler. Queue-insert triggers above are primary; cron drains retry/backlog jobs.
do $$
begin
  begin
    create extension if not exists pg_cron;
  exception when others then
    raise notice 'pg_cron unavailable; queue insert trigger remains active: %', sqlerrm;
  end;
end $$;

do $$
declare
  existing_job_id bigint;
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron')
     and exists (select 1 from pg_extension where extname = 'pg_net') then

    for existing_job_id in
      select jobid from cron.job
      where jobname in ('alameen-whatsapp-shadow-worker','alameen-whatsapp-v2-shadow-worker')
    loop
      perform cron.unschedule(existing_job_id);
    end loop;

    perform cron.schedule(
      'alameen-whatsapp-shadow-worker',
      '* * * * *',
      $cron$
      select net.http_post(
        url := 'https://www.ameenfinance.co/api/internal/whatsapp-shadow/worker',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-shadow-worker-token', (
            select value from public.whatsapp_shadow_settings where key = 'worker_token'
          )
        ),
        body := jsonb_build_object('source', 'supabase_cron')
      );
      $cron$
    );

    perform cron.schedule(
      'alameen-whatsapp-v2-shadow-worker',
      '* * * * *',
      $cron$
      select net.http_post(
        url := 'https://www.ameenfinance.co/api/internal/whatsapp-v2-shadow/worker',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-shadow-worker-token', (
            select value from public.whatsapp_shadow_settings where key = 'worker_token'
          )
        ),
        body := jsonb_build_object('source', 'supabase_cron')
      );
      $cron$
    );
  end if;
end $$;

-- Kick the legacy backlog once immediately after installation.
do $$
declare
  v_token text;
begin
  select value into v_token from public.whatsapp_shadow_settings where key = 'worker_token';
  if coalesce(v_token, '') <> '' then
    perform net.http_post(
      url := 'https://www.ameenfinance.co/api/internal/whatsapp-shadow/worker',
      headers := jsonb_build_object('Content-Type','application/json','x-shadow-worker-token',v_token),
      body := jsonb_build_object('source','phase0_migration_initial_kick')
    );
  end if;
end $$;

notify pgrst, 'reload schema';
