-- Dedicated Shadow queue and results storage.
-- Safe to run more than once.

create extension if not exists pgcrypto with schema extensions;
set search_path = public, extensions;

create table if not exists public.whatsapp_shadow_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.whatsapp_shadow_settings enable row level security;

insert into public.whatsapp_shadow_settings (key, value)
values ('worker_token', encode(gen_random_bytes(32), 'hex'))
on conflict (key) do nothing;

create table if not exists public.whatsapp_shadow_jobs (
  id uuid primary key default gen_random_uuid(),
  incoming_message_id text not null unique,
  wa_id text not null,
  customer_name text,
  customer_message text not null,
  message_type text not null default 'text',
  actual_reply text not null,
  initial_intent text,
  tracking_id text,
  application_id text,
  application_snapshot jsonb not null default '{}'::jsonb,
  conversation_snapshot jsonb not null default '{}'::jsonb,

  status text not null default 'queued'
    check (status in ('queued', 'processing', 'retry_wait', 'succeeded', 'blocked', 'dead_letter')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 3 check (max_attempts between 1 and 10),
  next_attempt_at timestamptz default now(),
  locked_at timestamptz,
  locked_by text,

  candidate_reply text,
  topics text[] not null default '{}',
  agent text,
  quality_score integer not null default 0 check (quality_score between 0 and 100),
  risk_flags text[] not null default '{}',
  answered_topics text[] not null default '{}',
  missing_topics text[] not null default '{}',
  facts jsonb not null default '{}'::jsonb,
  model text,
  provider_http_status integer,
  parse_mode text,
  generation_ms integer,
  last_error_code text,
  last_error_message text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.whatsapp_shadow_jobs enable row level security;

create index if not exists whatsapp_shadow_jobs_due_idx
  on public.whatsapp_shadow_jobs (status, next_attempt_at, created_at);
create index if not exists whatsapp_shadow_jobs_wa_id_idx
  on public.whatsapp_shadow_jobs (wa_id, created_at desc);
create index if not exists whatsapp_shadow_jobs_created_idx
  on public.whatsapp_shadow_jobs (created_at desc);

create table if not exists public.whatsapp_shadow_attempts (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.whatsapp_shadow_jobs(id) on delete cascade,
  job_attempt integer not null,
  provider_attempt integer not null,
  model text,
  started_at timestamptz,
  completed_at timestamptz,
  latency_ms integer,
  http_status integer,
  outcome text not null
    check (outcome in ('success', 'http_error', 'network_error', 'timeout', 'parse_error')),
  error_code text,
  error_message text,
  raw_response text,
  created_at timestamptz not null default now()
);

alter table public.whatsapp_shadow_attempts enable row level security;

create index if not exists whatsapp_shadow_attempts_job_idx
  on public.whatsapp_shadow_attempts (job_id, created_at desc);

create or replace function public.claim_whatsapp_shadow_jobs(
  p_worker_id text,
  p_limit integer default 2
)
returns setof public.whatsapp_shadow_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with selected as (
    select id
    from public.whatsapp_shadow_jobs
    where status in ('queued', 'retry_wait')
      and coalesce(next_attempt_at, now()) <= now()
      and attempt_count < max_attempts
    order by created_at asc
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 2), 5))
  ), claimed as (
    update public.whatsapp_shadow_jobs j
    set status = 'processing',
        attempt_count = j.attempt_count + 1,
        locked_at = now(),
        locked_by = p_worker_id,
        updated_at = now()
    from selected s
    where j.id = s.id
    returning j.*
  )
  select * from claimed;
end;
$$;

create or replace function public.requeue_stale_whatsapp_shadow_jobs(
  p_stale_minutes integer default 10
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  update public.whatsapp_shadow_jobs
  set status = case when attempt_count >= max_attempts then 'dead_letter' else 'retry_wait' end,
      next_attempt_at = case when attempt_count >= max_attempts then null else now() end,
      last_error_code = coalesce(last_error_code, 'stale_worker_lock'),
      last_error_message = coalesce(last_error_message, 'تم تحرير مهمة عالقة بعد انتهاء مهلة العامل.'),
      locked_at = null,
      locked_by = null,
      completed_at = case when attempt_count >= max_attempts then now() else completed_at end,
      updated_at = now()
  where status = 'processing'
    and locked_at < now() - make_interval(mins => greatest(1, coalesce(p_stale_minutes, 10)));

  get diagnostics affected = row_count;
  return affected;
end;
$$;

revoke all on function public.claim_whatsapp_shadow_jobs(text, integer) from public, anon, authenticated;
revoke all on function public.requeue_stale_whatsapp_shadow_jobs(integer) from public, anon, authenticated;
grant execute on function public.claim_whatsapp_shadow_jobs(text, integer) to service_role;
grant execute on function public.requeue_stale_whatsapp_shadow_jobs(integer) to service_role;

-- Background scheduler. If pg_cron/pg_net are unavailable, the queue still works
-- and can be processed from the admin page using the manual worker button.
do $$
begin
  begin
    execute 'create extension if not exists pg_net';
  exception when others then
    raise notice 'pg_net unavailable: %', sqlerrm;
  end;

  begin
    execute 'create extension if not exists pg_cron';
  exception when others then
    raise notice 'pg_cron unavailable: %', sqlerrm;
  end;
end $$;

do $$
declare
  existing_job_id bigint;
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron')
     and exists (select 1 from pg_extension where extname = 'pg_net') then
    for existing_job_id in
      select jobid from cron.job where jobname = 'alameen-whatsapp-shadow-worker'
    loop
      perform cron.unschedule(existing_job_id);
    end loop;

    perform cron.schedule(
      'alameen-whatsapp-shadow-worker',
      '* * * * *',
      $cron$
      select net.http_post(
        url := 'https://www.ameenfinance.co/api/internal/whatsapp-shadow/worker',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-shadow-worker-token', (
            select value from public.whatsapp_shadow_settings where key = 'worker_token'
          )
        ),
        body := jsonb_build_object('source', 'supabase_cron')
      );
      $cron$
    );
  end if;
exception when others then
  raise notice 'Shadow cron scheduling skipped: %', sqlerrm;
end $$;
